baseurl = "http://blog.duncanhall.net/"
canonifyurls = true
copyright = "Copyright &copy; 2018 - Duncan Hall"
enableEmoji = true
paginate = 3
pygmentsCodeFences = true
summaryLength = 30
theme = "kiera"
title = "blog.duncanhall.net"
[author]
facebook = ""
github = "duncanhall"
gitlab = ""
instagram = ""
linkedin = ""
name = "Duncan Hall"
twitter = "_duncanhall"
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
[params]
tagline = "A Hugo theme for creative and technical writing" 
