baseurl = "http://blog.duncanhall.net"
title = "blog.duncanhall.net"
copyright = "Copyright &copy; 2018 - Duncan Hall"
canonifyurls = true
theme = "kiera"

paginate = 3

summaryLength = 30
enableEmoji = true
pygmentsCodeFences = true

[author]
    name = "Duncan Hall"
    github = "duncanhall"
    gitlab = ""
    linkedin = ""
    facebook = ""
    twitter = "_duncanhall"
    instagram = ""

[params]
    tagline = "A Hugo theme for creative and technical writing"
