baseurl = "http://blog.duncanhall.net/"
defaultContentLanguage = "en"
destination = "dist"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableEmoji = true
hrefTargetBlank = false
languageCode = "en-gb"
languageLang = "en"
publishDir = "dist"
relativeURLs = false
theme = "hugo-theme-minos"
title = "blog.duncanhall.net"
[[menu.main]]
identifier = "home"
name = "Home"
url = "/"
weight = 1
[params]
author = "Duncan Hall"
description = "blog.duncanhall.net"
smarttoc = true
