---
upload_path: "/hugo/uploads/:year:/:month:/:day:"
frontmatter_file_url_template: "/uploads/:year:/:month:/:day:"
body_file_url_template: "/uploads/:year:/:month:/:day:"
new_page_extension: md
auto_deploy: true
admin_path: 
webhook_url: 
sections:
  posts:
    default_front_matter_template: posts
version: 0.37.1
