---
pages:
- posts/mounting-a-windows-directory-in-the-docker-vm--boot2docker-.md
- posts/actionscript-as3-textbutton-class.md
- posts/javascript-wave-equation.md
- posts/painting-particles-with-easeljs-and-coffee-physics.md
- posts/google-maps-flash-api-and-selectable-copyright-text.md
- posts/actionscript-path-correction-part-2.md
- posts/actionscript-path-correction---no-going-back-.md
- posts/ucd-and-agile-development-since-1936.md
- posts/as3-encoded-polyline.md
hide_body: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: date
  label: Date
  type: text
  hidden: false
  default: ''
- name: draft
  label: Draft
  type: boolean
  hidden: false
  default: true
- type: boolean
  name: archive
  label: Archive
